### ISSUE TITLE
Running PageantRelayNamedPipe.exe keeps saying Cannot find named pipe name in file

### ISSUE THREAD

**Issue by breisig** [Race666/wsl2-to-pageant-forwarder#1]
I am running Putty/Pageant 0.79 on Windows 11 Pro 64-bit and I have my Putty Pagent running at startup (with --openssh-config C:\Users\%UserName%\.ssh\pageant.conf). I verified the file exists in my home directory [example: c:\Users\testuser\.ssh\pageant.conf . I have updated my .ssh/config file which has the 'Include pageant.conf' in the config and when I use try to use the built in Windows SSH client, I can SSH without servers without issue. So i know that's all working.

However, Whenever I run PageantRelayNamedPipe.exe, I keep getting the following error

```
C:\Users\testuser\Downloads>PageantRelayNamedPipe.exe
Cannot find named pipe name in file C:\Users\testuser\.ssh\pageant.conf
```

I know the file exists and even if I try from the command prompt 'notepad C:\Users\testuser\.ssh\pageant.conf', I see the file contents from my .ssh/pageant.conf file [Example: IdentityAgent "//./pipe/pageant.testuser.6f6b4be51e62affacfd48b964aa50ce4b9f24c4ebb569320d01dc716372a7c61"].

Nothing seems to help. Any ideas?

**Comment by Race666** [comment]
Ok. Checked against 0.79: putty agent changed (from 0.78u1 -> 0.79)  the pipe path seperator from backslashes \ to slashes / . I have to adjust the 

`regex RegPipe = new Regex(@"IdentityAgent \\\\\.\\pipe\\(.+)");`

to accept both variants.

Update: released V1.1 of PageantRelayNamedPipe please check if it works.
